version: '3'
services:
  frontend:
    command: ["nginx", "-g", "daemon off;"]
    entrypoint: ['./scripts/docker-entry-production.sh']
    ports:
      - "5445:80"
    volumes:
      - "./frontend/docker/default.conf:/etc/nginx/conf.d/default.conf"


